# Этот файл настраивает анализатор кода (линтер)
linter:
  rules:
    # Требовать комментарии для всех публичных членов (классов, методов и т.д.)
    - public_member_api_docs
    # Требовать комментарии к библиотекам
    - package_api_docs